# Generated by Django 5.2.1 on 2025-05-11 06:06

from django.db import migrations
from decimal import Decimal


def populate_data(apps, schema_editor):
    Category = apps.get_model("orders", "Category")
    MenuItem = apps.get_model("orders", "MenuItem")

    main_courses, _ = Category.objects.get_or_create(
        name="Main Courses",
        defaults={"description": "Hearty and satisfying main dishes."},
    )
    soups, _ = Category.objects.get_or_create(
        name="Soups", defaults={"description": "Warm and comforting soups."}
    )
    desserts, _ = Category.objects.get_or_create(
        name="Desserts", defaults={"description": "Sweet treats to end your meal."}
    )
    drinks, _ = Category.objects.get_or_create(
        name="Drinks", defaults={"description": "Refreshing beverages."}
    )

    MenuItem.objects.get_or_create(
        name="Grilled Chicken Breast",
        category=main_courses,
        defaults={
            "description": "Tender grilled chicken served with seasonal vegetables.",
            "price": Decimal("15.99"),
            "available": True,
        },
    )
    MenuItem.objects.get_or_create(
        name="Tomato Soup",
        category=soups,
        defaults={
            "description": "Classic creamy tomato soup.",
            "price": Decimal("6.50"),
            "available": True,
        },
    )
    MenuItem.objects.get_or_create(
        name="Chocolate Lava Cake",
        category=desserts,
        defaults={
            "description": "Warm chocolate cake with a gooey center.",
            "price": Decimal("8.00"),
            "available": True,
        },
    )
    MenuItem.objects.get_or_create(
        name="Iced Tea",
        category=drinks,
        defaults={
            "description": "Freshly brewed iced tea.",
            "price": Decimal("3.00"),
            "available": True,
        },
    )


def remove_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=remove_data),
    ]
