# Generated by Django 5.2.1 on 2025-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_category_name_alter_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark as a featured item to display on home/special sections.",
            ),
        ),
    ]
