# Generated by Django 5.2.1 on 2025-05-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('North', 'Northern Region'), ('Central', 'Central Region'), ('South', 'Southern Region')], default='North', max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_guests_per_day', models.PositiveIntegerField(default=50, help_text='Maximum number of reservations allowed per day for this branch.')),
                ('map_embed_html', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=5)),
                ('mobile', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTimeSlotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slot', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.branch')),
            ],
            options={
                'unique_together': {('branch', 'weekday', 'time_slot')},
            },
        ),
    ]
