# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_branch_reservation_branchtimeslotcapacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gender',
        ),
    ]
