# Generated by Django 5.2.1 on 2025-05-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_contactmessage_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='max_guests_per_day',
        ),
    ]
