# Generated by Django 5.2.1 on 2025-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_branch_max_guests_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtimeslotcapacity',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
