# Generated by Django 5.2.1 on 2025-05-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_branchtimeslotcapacity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_orderable',
            field=models.BooleanField(default=False, verbose_name='Orderable'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_reservable',
            field=models.BooleanField(default=True, verbose_name='Reservable'),
        ),
    ]
