# Generated by Django 5.2.1 on 2025-05-30 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_branch_is_active_branch_is_orderable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.branch', verbose_name='Pickup Branch'),
            preserve_default=False,
        ),
    ]
