# Generated by Django 5.2.1 on 2025-05-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_pickup_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.branch', verbose_name='Pickup Branch'),
        ),
    ]
