# Generated by Django 5.2.1 on 2025-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
