# Generated by Django 5.2.1 on 2025-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_menuitem_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtimeslotcapacity',
            name='is_orderable',
            field=models.BooleanField(default=True, verbose_name='Orderable'),
        ),
        migrations.AddField(
            model_name='branchtimeslotcapacity',
            name='max_orderable',
            field=models.PositiveIntegerField(default=10, verbose_name='Max Orderable'),
        ),
    ]
