# Generated by Django 5.2.1 on 2025-06-01 01:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_branchtimeslotcapacity_is_orderable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=datetime.date(2025, 6, 1), help_text='The date for order pickup', verbose_name='Pickup Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.TimeField(default=datetime.time(12, 0), help_text='The time slot for order pickup', verbose_name='Pickup Time Slot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(help_text='Branch where the order will be picked up', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.branch', verbose_name='Pickup Branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Optional special instructions for the order', verbose_name='Special Instructions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
